apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-test
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: nginx
          name: myapp
          ports:
            - containerPort: 80